Pusaka.Web.NetCore/Controllers/MissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pusaka.Web.NetCore.Controllers
{
    public class MissionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pusaka.Web.NetCore/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pusaka.Web.NetCore.Controllers
{
    public class SchoolController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pusaka.Web.NetCore/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pusaka.Web.NetCore.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pusaka.Web.NetCore/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pusaka.Web.NetCore.Controllers
{
    public class VolunteerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pusaka.Web.NetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html dir="ltr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pusaka.Web.NetCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.1/css/fabric.min.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
        <link href="~/lib/datatable/datatables.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/9.6.1/css/fabric.min.css">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
        <link href="~/lib/datatable/datatables.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <partial name="_TopMenu" />

    <div class="container-fluid flex-fill d-flex">
        <div class="row flex-fill">
            <partial name="_SideMenu" />

            <main role="main" class="main w-85 pusaka-ml-15 p-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
        <script src="~/lib/datatable/datatables.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
        <script src="~/lib/datatable/datatables.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pusaka.Web.NetCore/Views/Shared/_SideMenu.cshtml
<nav class="sidebar border-right bg-light w-15 h-100 position-absolute">
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">Admin Configuration</h6>
    <div class="dropdown-divider"></div>
    <ul class="nav flex-column h-100">
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center" href="@Url.Action("Index", "User")">
                <i class="ms-Icon ms-Icon--People" aria-hidden="true"></i>
                Student
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center" href="@Url.Action("Index", "School")">
                <i class="ms-Icon ms-Icon--ConnectContacts" aria-hidden="true"></i>
                School
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center" href="@Url.Action("Index", "Volunteer")">
                <i class="ms-Icon ms-Icon--EngineeringGroup" aria-hidden="true"></i>
                Volunteer
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center" href="@Url.Action("Index", "Mission")">
                <i class="ms-Icon ms-Icon--GroupedList" aria-hidden="true"></i>
                Mission
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link d-flex align-items-center" href="@Url.Action("Index", "Roles")">
                <i class="ms-Icon ms-Icon--People" aria-hidden="true"></i>
                Roles
            </a>
        </li>
    </ul>
</nav>

Pusaka.Web.NetCore/Views/Shared/_TopMenu.cshtml
<nav class="navbar pusaka-top-bg align-items-center fmi-header d-print-block">
    <div class="navbar-brand">

    </div>
    <h5 class="navbar-text mr-auto mb-0">Pusaka Back Office</h5>
</nav>